# Generated by Django 3.1.1 on 2023-10-15 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeses', '0004_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='i_rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
